### PR TITLE
add gem version string to exec resource for uniqueness

### PR DESCRIPTION
**Pull request by rubyisbeautiful**
hey @justindowning thanks for the module.  I came across the issue of trying to upgrade some base gems in preparation for a ruby upgrade...specifically bundler in ruby 2.1.5 in preparation to upgrade to ruby 2.3.3.  So I attempted to add bundler version 1.13.6 to ruby 2.1.5 but it failed on duplicate resource, like so:
```
Duplicate declaration: Exec[gem-install-bundler-2.1.5] is already declared in file /etc/puppet/environments/dev/modules/rbenv/manifests/gem.pp:86; cannot redeclare at /etc/puppet/environments/dev/modules/rbenv/manifests/gem.pp:86
```

I think this PR addresses it safely, but it was like a ten minute effort.  Let me know if some more thought should be put into it.  Thanks!

### CODE REVIEW

**Comment by justindowning** [comment]
I'm not sure this is necessary. Gems are coupled with their ruby version--so if you have bundler 1.13.6 in ruby 2.1.5 and you want bundler 1.13.6 on ruby 2.3.3, there should not be a conflict.

The `rbenv::gem` define can already take a unique title to distinguish gems across ruby versions. See the [bundler](https://github.com/justindowning/puppet-rbenv/blob/0508129ed687f24563cc28d3c41a21e58200abac/manifests/build.pp#L146-L151) example for more details.

**Comment by rubyisbeautiful** [comment]
Let's say we have the default bundler that installed at ruby 2.1.5 time, 1.10.5 (or whatever).  If I add want to upgrade that via puppet and rbenv, I add something like:
```
rbenv::gem { "whatevs_my_unique_name" :
  gem => 'bundler',
  version => '1.13.6',
  ruby_version => '2.1.5',
}
   
```
will currently result in an 
```
exec { "gem-install-bundler-2.1.5":
...
```
which, is already declared from the the ruby 2.1.5 install itself, see https://github.com/justindowning/puppet-rbenv/blob/master/manifests/build.pp#L146

the unique title I give doesn't come into play in the Exec resource, if I name the gem, and now that I've taken more time to explain it, it looks like it may be unique to bundler, so I can modify the PR to focus on the bundler issue if you want :)

**Comment by justindowning** [comment]
@rubyisbeautiful Great explanation. I think it's wise to rename the `exec` to be unique to allow multiple versions of a single gem in a ruby install (like your bundler example).

Could you update your `exec` title to be:

    exec { "ruby-${ruby_version}-gem-install-${gem}-${version}":

This way we can have many-to-one gems to ruby. I don't think the $version RE is going to be necessary, though the default is `'>=0'`. What do you think?

**Comment by rubyisbeautiful** [comment]
I just assumed there was many potentially bad outcomes that could happen with an Exec...since `>` certainly is likely to have a meaning, and maybe `~` as in `~> 1.0.0` so I just went with subbing all the non digits out for underscores.  I think with an Exec, there are many possibilities for how the Exec is executed (i.e. various shells).  
The Exec title is captured in quotes but just seemed more likely to cause mischief if it ever got out of those quotes :)  I may have been overly cautious.  Your call sir!

**Comment by justindowning** [comment]
You're spot on. Can you update the PR to use this pattern for the exec (where version_for_exec is your RE)?

    exec { "ruby-${ruby_version}-gem-install-${gem}-${version_for_exec}":

**Comment by rubyisbeautiful** [comment]
I updated only that first `Exec` resource with the naming convention you mentioned (and the spec to match) -- I hope that was what you meant.  I didn't change the variable `$version_for_exec_name` to `$version_for_exec` as I assumed it was a typo and not a literal variable name change request - but I can :)

**Comment by justindowning** [comment]
💚  Thanks so much @rubyisbeautiful

**Pull request merged**
